/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.northeastern.hospital_management.view;

import com.northeastern.hospital_management.model.Admin;
import static com.northeastern.hospital_management.model.Admin.Role.SYSTEM_ADMIN;

/**
 *
 * @author imkus
 */
public class AdminView extends javax.swing.JPanel {

    /**
     * Creates new form AdminView
     *
     * @param admin
     */
    public AdminView(Admin admin) {
        initComponents();

        switch (admin.getRole()) {
            case SYSTEM_ADMIN -> {
                jTabbedPane1.add("Patient", new PatientCRUD());
                jTabbedPane1.add("Doctor", new DoctorCRUD());
                jTabbedPane1.add("Hospital", new HospitalCRUD());
                jTabbedPane1.add("Community", new CommunityCRUD());
            }
            case COMMUNITY_ADMIN ->
                jTabbedPane1.add("Community", new CommunityCRUD());
            case HOSPITAL_ADMIN -> {
                jTabbedPane1.add("Patient", new PatientCRUD());
                jTabbedPane1.add("Doctor", new DoctorCRUD());
                jTabbedPane1.add("Patient", new PatientCRUD());
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
